In [1]:
#Create a 10 x 10 matrix of random numbers
import numpy as np
import pandas as pd
matrix = np.random.rand(10,10)
matrix.shape

(10, 10)

In [5]:
# Create dataframe
df = pd.DataFrame(matrix)
df.describe() #to describe column-wise means

,0,1,2,3,4,5,6,7,8,9
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.384277,0.373115,0.286140,0.398437,0.519316,0.673726,0.428155,0.568574,0.385841,0.636068
std,0.272013,0.271825,0.202605,0.284611,0.313452,0.235672,0.298552,0.335863,0.364796,0.294635
min,0.067339,0.012735,0.017496,0.029401,0.116570,0.260067,0.120628,0.050948,0.034745,0.029419
25%,0.192682,0.256760,0.094112,0.166082,0.254296,0.604635,0.240024,0.361873,0.059555,0.441540
50%,0.337537,0.317828,0.298747,0.372585,0.543260,0.718217,0.286131,0.604766,0.244162,0.700905
75%,0.535854,0.488986,0.448709,0.572416,0.764862,0.857537,0.651708,0.887127,0.731682,0.840089
max,0.875407,0.863899,0.576081,0.903508,0.959089,0.905009,0.993800,0.926353,0.977453,0.973012

In [6]:
df.apply(pd.DataFrame.describe, axis=1) #describe row-wise means

   count      mean       std       min       25%       50%       75%       max
0   10.0  0.405780  0.328625  0.085281  0.144373  0.283482  0.691601  0.927383
1   10.0  0.632100  0.321854  0.067339  0.509279  0.736603  0.868909  0.959089
2   10.0  0.375456  0.242738  0.050948  0.234599  0.382476  0.419656  0.769236
3   10.0  0.497736  0.233293  0.116570  0.380303  0.568921  0.589748  0.847488
4   10.0  0.417774  0.290158  0.017496  0.238273  0.386412  0.675085  0.838244
5   10.0  0.506541  0.342023  0.012735  0.222444  0.545678  0.718984  0.993800
6   10.0  0.406167  0.324836  0.029401  0.187988  0.289995  0.699195  0.875407
7   10.0  0.378684  0.312122  0.031758  0.152802  0.341024  0.433629  0.908627
8   10.0  0.557860  0.290229  0.049052  0.303707  0.696765  0.711516  0.903508
9   10.0  0.475552  0.350299  0.084743  0.180139  0.390109  0.715648  0.977453